# Generated by Django 3.2 on 2021-04-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_name_comment_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='by',
            new_name='name',
        ),
    ]
