# Generated by Django 3.2.1 on 2021-05-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_by_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'articles'},
        ),
    ]
