# Generated by Django 3.2.4 on 2021-06-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
