# Generated by Django 3.2.4 on 2021-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', 'NEWS'), ('SPORTS', 'SPORTS'), ('POLITICS', 'POLITICS'), ('LIFESTYLE', 'LIFESTYLE'), ('FASHION', 'FASHION'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('BUSINESS', 'BUSINESS'), ('TECHNOLOGY', 'TECHONOLOGY')], max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Title should not be more than 15 words', max_length=150),
        ),
    ]
